name: Automerge release bump PR

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: { }

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "$TITLE"
      - name: Check Condition
        env:
          CONDITION: ${{ startsWith(github.event.pull_request.title, 'chore(release)') }}
        run: echo "$CONDITION"
  autoapprove:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.title, 'chore(release)') }}
    steps:
      - name: Autoapproving
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'github-actions' || github.actor == 'eresponseservices'
        with:
          github-token: "${{ secrets.DRM_GIT_HUB_TOKEN }}"

  automerge:
    needs: [ autoapprove ]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.title, 'chore(release)') }}
    steps:
      - name: Automerging
        uses: pascalgn/automerge-action@v0.7.5
        if: github.actor == 'github-actions' || github.actor == 'eresponseservices'
        env:
          GITHUB_TOKEN: "${{ secrets.DRM_GIT_HUB_TOKEN }}"
          GITHUB_LOGIN: cb911-bot
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "10000"
